const pair = (technique, q1, o1, a1, e1, q2, o2, a2, e2) => ({
  technique,
  exercises: [
    { label: "Original", q: q1, o: o1, a: a1, e: e1 },
    { label: "Twin", q: q2, o: o2, a: a2, e: e2 }
  ]
});

window.conceptCourses = {
  foundations: [
    { title: "Probability language", subtitle: "Outcomes, events, notation, and conditioning", take: 3, pairs: [
      pair("Identify the sample space", "A coin is tossed twice. Which is the sample space?", ["$\\{H,T\\}$","$\\{HH,HT,TH,TT\\}$","$\\{0,1,2\\}$","$\\{HH,TT\\}$"], 1, "List every complete outcome of both tosses.", "A die and coin are used together. Which describes one outcome?", ["$6$","Heads","$(4,H)$","$\\{1,\\ldots,6\\}$"], 2, "One outcome must record both parts of the experiment."),
      pair("Translate a complement", "If $A$ is ‘at least one head,’ what is $A^c$?", ["Exactly one head","No heads","Two heads","At least one tail"], 1, "The complement is everything outside $A$: zero heads.", "If $B$ is ‘a product is defective,’ what is $B^c$?", ["The product is not defective","Two products fail","At least one fails","The test is repeated"], 0, "Complement means the event does not occur."),
      pair("Distinguish union and intersection", "What does $A\\cap B$ mean?", ["$A$ only","$B$ only","Both $A$ and $B$","At least one"], 2, "Intersection is the overlap: both events occur.", "What does $A\\cup B$ mean?", ["Both only","Neither","Exactly one","At least one, possibly both"], 3, "Union includes $A$, $B$, and their overlap."),
      pair("Read conditional probability", "What does $P(A\\mid B)$ ask?", ["Probability of $B$ after $A$","Probability of $A$ after learning $B$","Probability of both without information","Probability of neither"], 1, "The event after the vertical bar is the information given.", "A card is known to be red. Which notation asks for the probability it is a heart?", ["$P(R\\mid H)$","$P(H\\cap R)$","$P(H\\mid R)$","$P(H\\cup R)$"], 2, "We want heart after learning red: $P(H\\mid R)$."),
      pair("Recognize independence", "If learning $A$ occurred does not change $P(B)$, the events are:", ["Mutually exclusive","Independent","Complements","Impossible"], 1, "Independence means one event supplies no probability information about the other.", "Which equation proves independence?", ["$P(A\\cap B)=0$","$P(A\\cup B)=1$","$P(A\\cap B)=P(A)P(B)$","$P(A)=P(B)$"], 2, "The product equation is the exact independence test.")
    ]},
    { title: "Counting, variables, samples, and data", subtitle: "The objects statistics calculates with", take: 99, pairs: [
      pair("Choose combinations when order does not matter", "How many committees of $2$ can be chosen from $5$ people?", ["$5$","$10$","$20$","$25$"], 1, "$\\binom52=10$ because changing order does not create a new committee.", "How many unordered teams of $3$ can be selected from $6$ students?", ["$18$","$20$","$120$","$216$"], 1, "$\\binom63=20$. A team has no first, second, or third position."),
      pair("Decide whether replacement creates dependence", "Cards are drawn without replacement. Are successive draws independent?", ["Yes","No","Only for red cards","Only with two draws"], 1, "The first draw changes the remaining deck, so later probabilities change.", "A selected name is returned before drawing again. What happens to selection probabilities?", ["They remain constant","They become zero","They always double","They depend on order"], 0, "Replacement restores the original population before each draw."),
      pair("Classify discrete versus continuous", "Which variable is continuous?", ["Number of calls","Exact waiting time","Number of children","Die result"], 1, "Waiting time can take any real value in an interval.", "Which variable is discrete?", ["Exact temperature","Exact weight","Number of defects","Exact height"], 2, "A count has separated integer values and is discrete."),
      pair("Separate population, parameter, sample, and statistic", "The true mean height of all students is a:", ["Sample","Statistic","Parameter","Outcome"], 2, "A population summary is a fixed parameter.", "The mean height of $40$ sampled students is a:", ["Statistic","Population","Parameter","Event"], 0, "A value calculated from observed sample data is a statistic."),
      pair("Recognize resistant summaries", "Which measure changes least when one huge outlier is added?", ["Mean","Range","Median","Maximum"], 2, "The median depends on order and middle position, not the outlier's magnitude.", "If only the largest observation increases, which usually stays unchanged?", ["Range","Mean","IQR","Maximum"], 2, "Quartiles describe central positions, so the IQR resists a changed extreme.")
    ]}
  ],

  probability: [
    { title: "Events, independence, and Bayes", subtitle: "Translate wording before calculating", take: 3, pairs: [
      pair("Use inclusion–exclusion", "Given $P(A)=0.5$, $P(B)=0.4$, $P(A\\cap B)=0.2$, find $P(A\\cup B)$.", ["$0.3$","$0.7$","$0.9$","$1.1$"], 1, "$0.5+0.4-0.2=0.7$; subtract the overlap once.", "Given $P(C)=0.6$, $P(D)=0.3$, $P(C\\cap D)=0.1$, find $P(C\\cup D)$.", ["$0.2$","$0.7$","$0.8$","$0.9$"], 2, "$0.6+0.3-0.1=0.8$."),
      pair("Use a complement for at least one", "Three independent items fail with probability $0.1$. Find the probability of at least one failure.", ["$0.001$","$0.271$","$0.729$","$0.900$"], 1, "$1-P(\\text{none})=1-0.9^3=0.271$.", "Four independent shots hit with probability $0.8$. Find the probability of at least one hit.", ["$0.0016$","$0.2000$","$0.4096$","$0.9984$"], 3, "$1-P(\\text{all miss})=1-0.2^4=0.9984$."),
      pair("Test independence numerically", "$P(A)=0.3$, $P(B)=0.5$, $P(A\\cap B)=0.15$. Are $A,B$ independent?", ["Yes","No","Only if disjoint","Unknown"], 0, "$P(A)P(B)=0.15$, exactly the intersection.", "$P(C)=0.4$, $P(D)=0.2$, $P(C\\cap D)=0.10$. Are $C,D$ independent?", ["Yes","No","They are complements","They are disjoint"], 1, "$P(C)P(D)=0.08\\ne0.10$."),
      pair("Compute conditional probability", "$P(A\\cap B)=0.18$ and $P(B)=0.30$. Find $P(A\\mid B)$.", ["$0.12$","$0.48$","$0.60$","$1.67$"], 2, "$P(A\\mid B)=0.18/0.30=0.60$.", "$P(C\\cap D)=0.12$ and $P(D)=0.40$. Find $P(C\\mid D)$.", ["$0.28$","$0.30$","$0.48$","$3.33$"], 1, "$0.12/0.40=0.30$."),
      pair("Reverse a condition with Bayes", "Prevalence is $0.02$, sensitivity $0.95$, false-positive rate $0.01$. Which is the numerator of $P(D\\mid +)$?", ["$0.95$","$0.02$","$0.95(0.02)$","$0.01(0.98)$"], 2, "The numerator is the true-positive population fraction $P(+\\mid D)P(D)$.", "Spam prevalence is $0.10$ and a filter flags spam with probability $0.90$. Which product is the true-flag fraction?", ["$0.90(0.10)$","$0.90(0.90)$","$0.10+0.90$","$0.10/0.90$"], 0, "True flagged spam is $P(F\\mid S)P(S)$. ")
    ]},
    { title: "Counting models", subtitle: "Binomial, multinomial, hypergeometric, and trees", take: 99, pairs: [
      pair("Recognize a binomial experiment", "Which is binomial?", ["Roll until first six","Count heads in $10$ independent tosses","Draw cards without replacement","Measure waiting time"], 1, "Fixed $n$, independent yes/no trials, constant $p$.", "Which is binomial?", ["Count responders among $20$ independent patients with constant response chance","Count plan A/B/C choices","Wait for first sale","Select jurors without replacement"], 0, "The patient story has the four binomial conditions."),
      pair("Use the binomial probability formula", "$X\\sim\\operatorname{Bin}(5,0.2)$. Which gives $P(X=2)$?", ["$\\binom52(0.2)^2(0.8)^3$","$(0.2)^2$","$\\binom52(0.8)^2(0.2)^3$","$1-(0.8)^5$"], 0, "Choose the two success positions, then multiply two successes and three failures.", "$Y\\sim\\operatorname{Bin}(6,0.7)$. Which gives $P(Y=4)$?", ["$\\binom64(0.7)^4(0.3)^2$","$\\binom64(0.3)^4(0.7)^2$","$(0.7)^4$","$1-(0.3)^6$"], 0, "Four successes and two failures can appear in $\\binom64$ orders."),
      pair("Use a multinomial count", "Ten choices fall into A/B/C with probabilities $.2,.3,.5$. Which factor counts arrangements of counts $2,3,5$?", ["$\\binom{10}2$","$10!/(2!3!5!)$","$2!3!5!$","$10^3$"], 1, "The multinomial coefficient arranges repeated category labels.", "Eight outcomes fall into red/blue/green with counts $1,2,5$. Which coefficient is used?", ["$8!/(1!2!5!)$","$\\binom81$","$1!2!5!/8!$","$8^3$"], 0, "Use $n!$ divided by every category-count factorial."),
      pair("Use hypergeometric sampling", "From $20$ people with $7$ supporters, choose $4$ without replacement. Which numerator gives exactly $3$ supporters?", ["$\\binom73\\binom{13}1$","$\\binom43$","$7^3(13)$","$\\binom{20}4$"], 0, "Choose $3$ of the $7$ supporters and $1$ of the $13$ others.", "From $15$ parts with $5$ defective, choose $3$ without replacement. Which numerator gives exactly $2$ defective?", ["$\\binom52\\binom{10}1$","$\\binom32$","$5^2(10)$","$\\binom{15}3$"], 0, "Choose two defective and one nondefective part."),
      pair("Multiply paths and add alternatives", "A player hits first with $.8$; after a miss the next chance is $.7$. What is $P(\\text{miss, then hit})$?", ["$.8(.7)$","$.2(.7)$","$.2(.3)$","$.8+.7$"], 1, "Multiply probabilities along the path: first miss $.2$, then hit $.7$.", "A machine works day 1 with $.9$; after failure, repair succeeds next day with $.6$. Find $P(\\text{fail, then repaired})$.", ["$.9(.6)$","$.1(.6)$","$.1(.4)$","$.9+.6$"], 1, "The path probability is $.1\\cdot.6$. ")
    ]}
  ],

  distributions: [
    { title: "Recognize the distribution", subtitle: "Match the experiment before touching formulas", take: 3, pairs: [
      pair("Binomial versus geometric", "Count successes in a fixed $n$: which model?", ["Geometric","Binomial","Poisson","Exponential"], 1, "A fixed finish with repeated yes/no trials is binomial.", "Count trials until the first success: which model?", ["Binomial","Uniform","Geometric","Normal"], 2, "A moving finish at first success is geometric."),
      pair("Poisson versus exponential", "Count arrivals during one hour: which model?", ["Poisson","Exponential","Uniform","Geometric"], 0, "Poisson models the count in an interval.", "Measure time until the next arrival: which model?", ["Poisson","Exponential","Binomial","Hypergeometric"], 1, "Exponential models the continuous wait."),
      pair("Recognize continuous uniform", "A random point is equally likely anywhere from $2$ to $8$. Which model?", ["$U(2,8)$","$N(2,8)$","$\\operatorname{Pois}(8)$","$\\operatorname{Geo}(2)$"], 0, "Equal probability per unit length on an interval is continuous uniform.", "A bus arrives at an equally likely time between 10:00 and 10:20. Which model fits minutes after 10:00?", ["$U(0,20)$","$\\operatorname{Bin}(20,.5)$","$N(0,20)$","$\\operatorname{Exp}(20)$"], 0, "Every time in the bounded interval is equally likely."),
      pair("Recognize normal data", "Which story most naturally suggests a normal model?", ["Rare defect counts","Adult measurement clustered symmetrically around a mean","Trials until success","Cards without replacement"], 1, "Normal models continuous measurements with a symmetric bell shape.", "Which is least suitable for a normal model?", ["Measurement error","Manufactured diameter","Number of arrivals in a minute","Adult height"], 2, "A small nonnegative count is naturally Poisson, not normal."),
      pair("Recognize hypergeometric dependence", "Which model counts red cards in $5$ draws without replacement?", ["Binomial","Hypergeometric","Poisson","Geometric"], 1, "Finite sampling without replacement is hypergeometric.", "Which model counts vaccinated people in a random sample from a fixed list without replacement?", ["Hypergeometric","Binomial","Exponential","Uniform"], 0, "The population composition changes after each selection.")
    ]},
    { title: "Calculate with named distributions", subtitle: "Parameters, tails, means, and variances", take: 99, pairs: [
      pair("Use a geometric tail", "$X\\sim\\operatorname{Geo}(.2)$. Find $P(X&gt;3)$.", ["$.2^3$","$.8^3$","$1-.8^3$","$.8^2(.2)$"], 1, "More than three trials means three consecutive failures: $.8^3$.", "$Y\\sim\\operatorname{Geo}(.4)$. Find $P(Y&gt;2)$.", ["$.4^2$","$.6^2$","$1-.6^2$","$.6(.4)$"], 1, "Two initial failures give $.6^2$."),
      pair("Recall Poisson mean and variance", "$X\\sim\\operatorname{Pois}(6)$. What is $\\operatorname{Var}(X)$?", ["$\\sqrt6$","$6$","$36$","$1/6$"], 1, "For Poisson, mean and variance both equal $\\lambda$.", "$Y\\sim\\operatorname{Pois}(2.5)$. What is $E[Y]$?", ["$1.25$","$2.5$","$6.25$","$\\sqrt{2.5}$"], 1, "The Poisson parameter is the expected count."),
      pair("Convert exponential mean and rate", "An exponential wait has mean $4$. Find $\\lambda$.", ["$4$","$1/4$","$1/16$","$16$"], 1, "$E[X]=1/\\lambda$, so invert the mean.", "An exponential wait has rate $\\lambda=0.2$. Find its mean.", ["$.04$","$.2$","$5$","$20$"], 2, "$1/.2=5$."),
      pair("Use uniform length ratios", "$X\\sim U(0,10)$. Find $P(2\\le X\\le5)$.", ["$.2$","$.3$","$.5$","$.7$"], 1, "Favorable length $3$ divided by total length $10$.", "$Y\\sim U(4,12)$. Find $P(6\\le Y\\le10)$.", ["$.25$","$.4$","$.5$","$.75$"], 2, "Favorable length $4$ over total length $8$ gives $.5$."),
      pair("Transform a normal variable", "$X\\sim N(10,2^2)$ and $Y=3X+1$. Find $E[Y]$.", ["$13$","$30$","$31$","$61$"], 2, "$E[Y]=3E[X]+1=31$.", "$X\\sim N(5,4^2)$ and $W=2X-3$. Find $\\operatorname{Var}(W)$.", ["$5$","$8$","$16$","$64$"], 3, "Variance scales by the square: $2^2(4^2)=64$.")
    ]}
  ],

  moments: [
    { title: "Expectation, variance, and joint distributions", subtitle: "Summarize random variables and their relationships", take: 3, pairs: [
      pair("Compute expectation", "$X=0,1,2$ with probabilities $.2,.5,.3$. Find $E[X]$.", ["$.8$","$1$","$1.1$","$1.5$"], 2, "$0(.2)+1(.5)+2(.3)=1.1$.", "$Y=1,2,3$ with probabilities $.3,.4,.3$. Find $E[Y]$.", ["$1.7$","$2$","$2.3$","$6$"], 1, "$1(.3)+2(.4)+3(.3)=2$."),
      pair("Use $E[X^2]-E[X]^2$", "$E[X]=3$, $E[X^2]=13$. Find $\\operatorname{Var}(X)$.", ["$4$","$9$","$10$","$13$"], 0, "$13-3^2=4$.", "$E[Y]=2$, $E[Y^2]=7$. Find $\\operatorname{Var}(Y)$.", ["$3$","$4$","$5$","$7$"], 0, "$7-2^2=3$."),
      pair("Find a marginal", "A joint-table row is $.10,.15,.25$. Its marginal is:", ["$.15$","$.25$","$.40$","$.50$"], 3, "Add the row cells: $.50$.", "A joint-table column is $.05,.20,.30$. Its marginal is:", ["$.25$","$.50$","$.55$","$.60$"], 2, "Add the column cells: $.55$."),
      pair("Compute covariance", "$E[XY]=8$, $E[X]=2$, $E[Y]=3$. Find covariance.", ["$2$","$3$","$6$","$8$"], 0, "$8-(2)(3)=2$.", "$E[UV]=5$, $E[U]=1$, $E[V]=4$. Find covariance.", ["$0$","$1$","$4$","$5$"], 1, "$5-(1)(4)=1$."),
      pair("Interpret correlation", "$\\rho=-.9$ means:", ["Strong negative linear association","Weak negative","Strong positive","Impossible"], 0, "Negative sign and magnitude near $1$ means strong negative linear association.", "$\\rho=.15$ means:", ["Strong negative","Weak positive linear association","Perfect positive","Impossible"], 1, "Positive sign but magnitude near $0$ means weak positive linear association.")
    ]},
    { title: "Linear combinations and estimators", subtitle: "Transform means, variances, and covariance", take: 99, pairs: [
      pair("Transform expectation", "$E[X]=4$. Find $E[3X-2]$.", ["$6$","$10$","$12$","$14$"], 1, "$3(4)-2=10$.", "$E[Y]=5$. Find $E[2Y+7]$.", ["$12$","$17$","$24$","$35$"], 1, "$2(5)+7=17$."),
      pair("Scale variance", "$\\operatorname{Var}(X)=5$. Find $\\operatorname{Var}(3X+1)$.", ["$15$","$16$","$45$","$46$"], 2, "$3^2(5)=45$; shifts do not affect variance.", "$\\operatorname{Var}(Y)=4$. Find $\\operatorname{Var}(-2Y+9)$.", ["$-8$","$8$","$16$","$25$"], 2, "$(-2)^2(4)=16$."),
      pair("Include covariance", "Variances are $4,9$ and covariance $2$. Find $\\operatorname{Var}(X+Y)$.", ["$11$","$13$","$15$","$17$"], 3, "$4+9+2(2)=17$.", "Variances are $3,5$ and covariance $-1$. Find $\\operatorname{Var}(U+V)$.", ["$6$","$7$","$8$","$10$"], 0, "$3+5+2(-1)=6$."),
      pair("Exploit a shared term", "Independent $X,Y$ and $\\operatorname{Var}(X)=6$. Find $\\operatorname{Cov}(X+Y,X)$.", ["$0$","$6$","$12$","Unknown"], 1, "Only the shared $X$ contributes: $\\operatorname{Var}(X)=6$.", "Independent $A,B$ and $\\operatorname{Var}(B)=4$. Find $\\operatorname{Cov}(A+B,B)$.", ["$0$","$2$","$4$","$8$"], 2, "Only shared $B$ contributes its variance."),
      pair("Check unbiasedness", "$E[T]=\\theta$. Then $T$ is:", ["Biased","Unbiased","A parameter","Constant"], 1, "Its repeated-sample mean equals the target.", "$E[W]=.8\\theta$. Then $W$ is:", ["Unbiased","Biased downward","Biased upward","Variance-free"], 1, "Its expected value falls below the target.")
    ]}
  ],

  clt: [
    { title: "Normal standardization and percentiles", subtitle: "Turn values into areas and back", take: 2, pairs: [
      pair("Compute a Z-score", "Mean $50$, SD $10$: Z-score of $65$?", ["$.5$","$1$","$1.5$","$6.5$"], 2, "$(65-50)/10=1.5$.", "Mean $100$, SD $20$: Z-score of $70$?", ["$-1.5$","$-.5$","$1.5$","$3.5$"], 0, "$(70-100)/20=-1.5$."),
      pair("Use left and right tails", "$\\Phi(1.2)=.8849$. Find $P(Z&gt;1.2)$.", ["$.1151$","$.8849$","$.9425$","$1.2$"], 0, "$1-.8849=.1151$.", "$\\Phi(-.5)=.3085$. Find $P(Z\\le-.5)$.", ["$.1915$","$.3085$","$.5$","$.6915$"], 1, "$\\Phi$ is already the left-tail area."),
      pair("Find interval probability", "$\\Phi(1)=.8413$. Find $P(0&lt;Z&lt;1)$.", ["$.1587$","$.3413$","$.5$","$.8413$"], 1, "$.8413-.5=.3413$.", "$\\Phi(.5)=.6915$, $\\Phi(-.5)=.3085$. Find the middle area.", ["$.1915$","$.3085$","$.3830$","$.6915$"], 2, "$.6915-.3085=.3830$."),
      pair("Reverse a percentile", "$X\\sim N(100,15^2)$, $z_{.9}=1.282$. Find $x_{.9}$.", ["$81$","$101$","$115$","$119.2$"], 3, "$100+1.282(15)=119.2$ approximately.", "$Y\\sim N(40,5^2)$, $z_{.1}=-1.282$. Find $y_{.1}$.", ["$33.6$","$38.7$","$41.3$","$46.4$"], 0, "$40-1.282(5)=33.6$ approximately."),
      pair("Add independent normals", "Four iid $N(3,2^2)$ variables are summed. Sum mean?", ["$3$","$6$","$12$","$16$"], 2, "Add means: $4(3)=12$.", "Nine iid $N(5,3^2)$ variables are summed. Sum SD?", ["$3$","$9$","$27$","$81$"], 1, "Add variances, then root: $3\\sqrt9=9$.")
    ]},
    { title: "Sampling distributions and CLT", subtitle: "Distinguish sums, averages, and discrete approximations", take: 99, pairs: [
      pair("Recognize iid", "iid means:", ["Independent, different distributions","Independent, same distribution","Normal only","Identical values"], 1, "iid is independent and identically distributed.", "Which violates iid?", ["Independent coin tosses","One observation changes the next distribution","Random sample from one stable population","Independent lifetimes"], 1, "Dependence violates iid."),
      pair("Distinguish sum and mean", "$\\mu=8$, $n=25$. Find $E[\\bar X]$.", ["$.32$","$8$","$40$","$200$"], 1, "The average remains centered at $\\mu$.", "$\\mu=8$, $n=25$. Find $E[S_{25}]$.", ["$8$","$25$","$40$","$200$"], 3, "The sum mean is $n\\mu=200$."),
      pair("Compute standard error", "$\\sigma=12$, $n=36$. Find $SE(\\bar X)$.", ["$1/3$","$2$","$12$","$72$"], 1, "$12/6=2$.", "$\\sigma=10$, $n=100$. Find $SE(\\bar X)$.", ["$.1$","$1$","$10$","$100$"], 1, "$10/10=1$."),
      pair("Apply continuity correction", "Approximate $P(X\\ge20)$. Use boundary:", ["$19$","$19.5$","$20$","$20.5$"], 1, "Including $20$ starts at $19.5$.", "Approximate $P(X\\le12)$. Use boundary:", ["$11.5$","$12$","$12.5$","$13$"], 2, "Including $12$ ends at $12.5$."),
      pair("Check binomial approximation", "$n=100,p=.4$: are normal conditions good?", ["Yes: $40,60$","No","Only if $p=.5$","Need known $\\sigma$"], 0, "Both $np$ and $n(1-p)$ are large.", "$n=20,p=.02$: are normal conditions good?", ["Yes","No: $np=.4$","Only for right tails","Always"], 1, "Expected successes are too few.")
    ]}
  ],

  estimation: [
    { title: "Confidence intervals", subtitle: "Estimate a parameter with a defensible margin", take: 3, pairs: [
      pair("Match parameter and estimator", "What estimates $\\mu$?", ["$\\bar X$","$\\sigma$","$p$","$z$"], 0, "Sample mean estimates population mean.", "What estimates $p$?", ["$\\mu$","$\\hat p$","$s$","$t$"], 1, "Sample proportion estimates population proportion."),
      pair("Interpret confidence", "A $95\\%$ method means:", ["Parameter changes","$95\\%$ of repeated intervals capture the parameter","All data are inside","The null is true"], 1, "Confidence is the long-run coverage of the method.", "Preferred wording after computing an interval?", ["Parameter has $.95$ probability","We are $95\\%$ confident it captures the parameter","$95\\%$ of people are inside","Estimate is exact"], 1, "The fixed interval is described using confidence, not parameter probability."),
      pair("Choose Z or t", "Normal mean, unknown $\\sigma$, $n=15$: use:", ["$z$","$t_{14}$","$t_{15}$","$\\chi^2$"], 1, "Unknown $\\sigma$ gives $t$ with $n-1$ df.", "Mean with known population $\\sigma$: use:", ["$z$","$t$ only","Poisson","F"], 0, "Known $\\sigma$ uses a Z critical value."),
      pair("Build an interval", "$\\bar x=20,\\sigma=4,n=16,z^*=2$. Interval?", ["$[18,22]$","$[16,24]$","$[19,21]$","$[12,28]$"], 0, "$SE=1$, margin $2$.", "$\\bar x=50,\\sigma=10,n=25,z^*=2$. Interval?", ["$[48,52]$","$[46,54]$","$[40,60]$","$[30,70]$"], 1, "$SE=2$, margin $4$."),
      pair("Reverse an interval", "$[8,14]$: center and margin?", ["$8,6$","$11,3$","$11,6$","$14,3$"], 1, "Midpoint $11$, half-length $3$.", "$[21,29]$: center and margin?", ["$21,8$","$25,4$","$25,8$","$29,4$"], 1, "Midpoint $25$, half-length $4$.")
    ]},
    { title: "Sample size and precision", subtitle: "Plan interval width before collecting data", take: 99, pairs: [
      pair("Convert length to margin", "Total length $.10$: margin?", ["$.02$","$.05$","$.10$","$.20$"], 1, "Margin is half the length.", "Total length $.06$: margin?", ["$.03$","$.06$","$.12$","$.003$"], 0, "Half of $.06$ is $.03$."),
      pair("Solve mean sample size", "$z^*=2,\\sigma=6,d=2$. Minimum $n$?", ["$6$","$9$","$18$","$36$"], 3, "$(2\\cdot6/2)^2=36$.", "$z^*=2,\\sigma=5,d=1$. Minimum $n$?", ["$10$","$25$","$50$","$100$"], 3, "$(2\\cdot5)^2=100$."),
      pair("Use worst-case proportion", "Unknown $p$: conservative $p(1-p)$?", ["$0$","$.1$","$.25$","$.5$"], 2, "Maximum occurs at $p=.5$.", "Why use $p=.5$ for planning?", ["Minimizes width","Maximizes variance","Makes $z=0$","Assumes pairing"], 1, "Maximum variance guarantees the target precision."),
      pair("Round upward", "$n\\ge84.02$: minimum integer?", ["$84$","$85$","$84.02$","$86$"], 1, "Round up to keep the inequality true.", "$n\\ge120.00$: minimum integer?", ["$119$","$120$","$121$","$120.5$"], 1, "It is already an integer."),
      pair("Predict width", "Multiply $n$ by $4$: standard error becomes:", ["Four times","Twice","Half","Quarter"], 2, "$SE\\propto1/\\sqrt n$.", "Increase confidence with same data: interval width:", ["Decreases","Unchanged","Increases","Zero"], 2, "A larger critical value widens it.")
    ]}
  ],

  testing: [
    { title: "Hypotheses, tails, p-values, and errors", subtitle: "Turn a research claim into a decision", take: 3, pairs: [
      pair("Write the alternative", "Claim: mean decreased from $50$. Choose $H_1$.", ["$\\mu=50$","$\\mu\\ne50$","$\\mu&lt;50$","$\\bar X&lt;50$"], 2, "‘Decreased’ is a left-tailed claim about population mean $\\mu$.", "Claim: proportion increased from $.4$. Choose $H_1$.", ["$p=.4$","$p&gt;.4$","$\\hat p&gt;.4$","$p\\ne.4$"], 1, "‘Increased’ gives a right-tailed population claim."),
      pair("Choose the tail", "Claim: the mean changed. Which test?", ["Left-tailed","Right-tailed","Two-tailed","No test"], 2, "‘Changed’ allows either direction.", "Claim: the defect rate is lower. Which test?", ["Left-tailed","Right-tailed","Two-tailed","Upper confidence only"], 0, "‘Lower’ places extreme evidence in the left tail."),
      pair("Interpret a p-value", "$p$-value $.03$ means:", ["$P(H_0)=.03$","Assuming $H_0$, equally or more extreme data have probability $.03$","Effect has probability $.97$","Type II error is $.03$"], 1, "The p-value is calculated under the null; it is not the probability the null is true.", "$p$-value $.20$ means:", ["Null is true with probability $.8$","Data are not very unusual under $H_0$","Alternative is impossible","Power is $.2$"], 1, "A large p-value means the sample is not surprising under the null."),
      pair("Compare p-value with alpha", "$p=.032$, $\\alpha=.05$. Decision?", ["Reject $H_0$","Do not reject $H_0$","Accept $H_0$","Change $p$"], 0, "$p\\le\\alpha$, so reject.", "$p=.08$, $\\alpha=.05$. Decision?", ["Reject","Do not reject","Prove null","Double alpha"], 1, "$p&gt;\\alpha$, so evidence is insufficient to reject."),
      pair("Distinguish errors and power", "Rejecting a true $H_0$ is:", ["Type I","Type II","Power","Confidence"], 0, "Type I error has probability $\\alpha$.", "Failing to reject a false $H_0$ is:", ["Type I","Type II","Power","Significance"], 1, "Type II error has probability $\\beta$; power is $1-\\beta$.")
    ]},
    { title: "Test statistics and output", subtitle: "Standardize evidence with the correct null model", take: 99, pairs: [
      pair("Use a one-mean Z statistic", "$\\bar x=54,\\mu_0=50,\\sigma=8,n=16$. Find $Z$.", ["$.5$","$1$","$2$","$4$"], 2, "$SE=8/4=2$ and $Z=(54-50)/2=2$.", "$\\bar x=98,\\mu_0=100,\\sigma=10,n=25$. Find $Z$.", ["$-2$","$-1$","$1$","$2$"], 1, "$SE=2$ and $Z=-2/2=-1$."),
      pair("Use t when sigma is unknown", "Normal sample, unknown $\\sigma$, $n=12$. Reference distribution?", ["$Z$","$t_{11}$","$t_{12}$","$F_{12}$"], 1, "Estimate $\\sigma$ with $s$ and use $n-1=11$ df.", "Normal sample, unknown $\\sigma$, $n=20$. Reference distribution?", ["$t_{19}$","$t_{20}$","$Z$ always","$\\chi^2_{20}$"], 0, "One-sample t has $19$ df."),
      pair("Use $p_0$ in a proportion test", "Test $H_0:p=.6$ with $n=100$. Which null SE?", ["$\\sqrt{\\hat p(1-\\hat p)/100}$","$\\sqrt{.6(.4)/100}$","$.6/100$","$.4/10$"], 1, "A test measures surprise under the claimed $p_0=.6$.", "Test $H_0:p=.2$ with $n=200$. Which null variance term?", ["$.2(.8)/200$","$\\hat p^2/200$","$.2/200$","$.8/200$"], 0, "Use $p_0(1-p_0)/n$."),
      pair("Use the CI-test bridge", "A $95\\%$ CI for $\\mu$ is $[2,7]$. Test $H_0:\\mu=0$ two-sided at $.05$.", ["Reject","Do not reject","Need raw data","Accept null"], 0, "The matching interval excludes the null value.", "A $95\\%$ CI is $[-1,4]$. Test $H_0:\\mu=0$ two-sided at $.05$.", ["Reject","Do not reject","Always reject","Use $.10$"], 1, "The interval contains zero."),
      pair("Convert Excel tails", "Excel gives positive $t$ and two-tail $p=.08$. Agreeing right-tail $p$?", ["$.02$","$.04$","$.08$","$.16$"], 1, "Same-direction one-tail value is half: $.04$.", "Excel gives negative $t$ and two-tail $p=.06$. Agreeing left-tail $p$?", ["$.03$","$.06$","$.12$","$.97$"], 0, "The observed sign agrees with the left alternative, so halve it.")
    ]}
  ],

  twosample: [
    { title: "Paired versus independent designs", subtitle: "The data collection determines the test", take: 2, pairs: [
      pair("Recognize pairing", "Same patients measured before and after: design?", ["Independent","Paired","Multinomial","Goodness-of-fit"], 1, "Each person supplies a linked pair.", "Two unrelated classes are sampled: design?", ["Paired","Independent","Repeated measures","Matched"], 1, "No observation in one class has a designated partner in the other."),
      pair("Create paired differences", "Before $X$, after $Y$, improvement means decrease. Useful difference?", ["$D=X-Y$","$D=X+Y$","$D=XY$","Separate means only"], 0, "Before minus after is positive when the measurement decreases.", "Machine A and B measure the same items; compare A minus B. Define:", ["$D=A-B$","$D=A+B$","Two independent samples","$D=A/B$ only"], 0, "One difference per item preserves pairing."),
      pair("Compute paired df", "$18$ complete pairs: paired t df?", ["$16$","$17$","$18$","$36$"], 1, "There are $18$ differences, so df $=18-1$.", "$25$ matched pairs: paired t df?", ["$23$","$24$","$25$","$48$"], 1, "$25-1=24$."),
      pair("Understand pairing's variance benefit", "Positive within-pair covariance affects $\\operatorname{Var}(X-Y)$ how?", ["Increases it","Decreases it through $-2\\operatorname{Cov}$","No effect","Makes it negative"], 1, "Positive covariance is subtracted twice.", "Why can matching improve precision?", ["It removes all bias","It controls shared unit-to-unit variation","It doubles sample size","It makes data independent"], 1, "Within-pair similarity cancels in differences."),
      pair("Variance of independent mean difference", "$\\sigma_X^2/n_X=.2$, $\\sigma_Y^2/n_Y=.3$. Find variance of $\\bar X-\\bar Y$.", ["$.1$","$.5$","$.6$","$1.5$"], 1, "Independent variances add: $.5$.", "Terms are $.4$ and $.1$. Difference variance?", ["$.3$","$.4$","$.5$","$.04$"], 2, "Add independent variance terms: $.5$.")
    ]},
    { title: "Two-sample t procedures and Excel", subtitle: "Read assumptions, degrees of freedom, and tails", take: 99, pairs: [
      pair("Recognize pooling", "When is pooled t appropriate?", ["Paired data","Independent groups with equal population variances","Known variances","Categorical counts"], 1, "Pooling assumes one common unknown variance.", "If equal variances are not assumed, prefer:", ["Paired t","Welch/unequal-variance t","One-proportion Z","Chi-square"], 1, "Welch does not impose a common population variance."),
      pair("Compute pooled df", "$n_X=10,n_Y=12$. Pooled t df?", ["$18$","$20$","$21$","$22$"], 1, "$10+12-2=20$.", "$n_X=16,n_Y=16$. Pooled t df?", ["$15$","$30$","$31$","$32$"], 1, "$16+16-2=30$."),
      pair("Interpret hypothesized difference", "Excel says hypothesized mean difference $0$. This represents:", ["$H_0:\\mu_X-\\mu_Y=0$","Observed means equal","Variances equal","Samples paired"], 0, "It is the null difference used in the numerator.", "Hypothesized difference $5$ represents:", ["$H_0:\\mu_X=5$","$H_0:\\mu_X-\\mu_Y=5$","Observed difference is $5$","SE is $5$"], 1, "The null specifies a population mean difference."),
      pair("Read the sign of t", "For statistic based on $\\bar X-\\bar Y$, $t&lt;0$ means:", ["$\\bar X&gt;\\bar Y$","$\\bar X&lt;\\bar Y$ relative to null","Always significant","Variances unequal"], 1, "The observed difference lies below the hypothesized difference.", "$t&gt;0$ with null difference $0$ means:", ["Observed $\\bar X-\\bar Y&gt;0$","$\\bar X&lt;\\bar Y$","Null is true","p-value is negative"], 0, "The standardized observed difference is positive."),
      pair("Choose paired or independent Excel output", "Before/after data but Excel output says two-sample independent. Main issue?", ["Nothing","Wrong design; should analyze differences","Need more confidence","Use chi-square"], 1, "Two columns do not erase subject pairing.", "Two unrelated groups but output says paired t. Main issue?", ["Correct automatically","Pairs have no meaningful link","Sample sizes must differ","p-value must be doubled"], 1, "A paired test requires meaningful one-to-one matching.")
    ]}
  ],

  regression: [
    { title: "Regression and ANOVA", subtitle: "Fit a line and account for variation", take: 3, pairs: [
      pair("Interpret slope", "$\\hat y=2+3x$. What does slope $3$ mean?", ["Predicted $Y$ is $3$ at $x=0$","Each one-unit $x$ increase raises predicted $Y$ by $3$","Correlation is $3$","Residual is $3$"], 1, "Slope is predicted response change per one-unit predictor increase.", "$\\hat y=10-.5x$. Interpret slope.", ["Each unit of $x$ lowers predicted $Y$ by $.5$","Intercept is $-.5$","Correlation is $.5$","$Y$ is always negative"], 0, "The fitted response decreases by $.5$ per unit."),
      pair("Compute a prediction and residual", "$\\hat y=1+2x$, $x=3$, observed $y=9$. Residual?", ["$2$","$7$","$8$","$9$"], 0, "Prediction $7$; residual $9-7=2$.", "$\\hat y=4+x$, $x=5$, observed $y=7$. Residual?", ["$-2$","$2$","$7$","$9$"], 0, "Prediction $9$; residual $7-9=-2$."),
      pair("Use variance decomposition", "$SST=100$, $SSE=30$. Find $SSR$.", ["$30$","$70$","$100$","$130$"], 1, "$SSR=SST-SSE=70$.", "$SST=80$, $SSR=50$. Find $SSE$.", ["$30$","$50$","$80$","$130$"], 0, "$SSE=80-50=30$."),
      pair("Compute and interpret R-squared", "$SST=80$, $SSE=20$. Find $R^2$.", ["$.20$","$.25$","$.75$","$4$"], 2, "$1-20/80=.75$: model explains $75\\%$ of response variation.", "$SSR=45$, $SST=60$. Find $R^2$.", ["$.25$","$.60$","$.75$","$1.33$"], 2, "$45/60=.75$."),
      pair("Connect F and t", "Slope test $t=-2.5$. Regression $F$?", ["$-6.25$","$-2.5$","$2.5$","$6.25$"], 3, "In simple regression $F=t^2=6.25$.", "Regression $F=9$. What is $|t|$ for the slope?", ["$3$","$4.5$","$9$","$81$"], 0, "$|t|=\\sqrt9=3$. ")
    ]},
    { title: "Chi-square goodness-of-fit", subtitle: "Compare observed category counts with a claimed model", take: 99, pairs: [
      pair("Compute expected counts", "$n=100$, claimed category probability $.3$. Expected count?", ["$.3$","$3$","$30$","$70$"], 2, "$E=np=30$.", "$n=200$, claimed probability $.15$. Expected count?", ["$15$","$30$","$85$","$170$"], 1, "$200(.15)=30$."),
      pair("Read a chi-square contribution", "$O=12,E=10$. Contribution?", ["$.2$","$.4$","$2$","$4$"], 1, "$(12-10)^2/10=4/10=.4$.", "$O=18,E=20$. Contribution?", ["$.2$","$.4$","$2$","$4$"], 0, "$(-2)^2/20=.2$."),
      pair("Compute goodness-of-fit df", "$5$ final categories, no parameters estimated. df?", ["$3$","$4$","$5$","$6$"], 1, "$k-1=4$.", "$7$ final categories, no parameters estimated. df?", ["$5$","$6$","$7$","$8$"], 1, "$7-1=6$."),
      pair("Subtract estimated parameters", "$6$ categories and one fitted parameter. df?", ["$3$","$4$","$5$","$6$"], 1, "$6-1-1=4$.", "$8$ categories and two fitted parameters. df?", ["$4$","$5$","$6$","$7$"], 1, "$8-1-2=5$."),
      pair("Handle small expected counts", "A category has expected count $1.2$. Best response?", ["Ignore it","Combine with a sensible neighboring category","Change observed count","Use a left-tail test"], 1, "Small expected counts undermine the approximation; combine categories before computing.", "After combining two tail categories, what must be updated?", ["Only observed counts","Only expected counts","Observed/expected counts and number of categories","Nothing"], 2, "Both counts combine, and the final category count changes df.")
    ]}
  ]
};
